#name: my workflow                     # Workflow 이름

#on:
#  push:
#    path:
#      - 'client/*'                    # Event 감지

#jobs:                                 # Job 설정
#  build:                              # Job ID
#    name: client action         # Job 이름
#    runs-on: ubuntu-18.04             # Job 가상환경 인스턴스
#    steps:                            # Steps
#      - name: checkout source code    # Step 이름
#       uses: actions/checkout@master # Uses를 통한 외부 설정 가져오기: 자신의 레포지토리 소스 받아오기

#      - name: echo Hello              # Step 이름
#        run: echo "Hello" 

name: React build
on: 
  push:                               # master Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.   # 레포지토리 체크아웃
        uses: actions/checkout@master
      - name: Cache node modules      # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: client/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-        

      - name: Install Dependencies    # 의존 파일 설치
        run: npm install
        working-directory: client

      - name: Build                   # React Build
        run: npm run build
        working-directory: client
        
      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'deploy-practice-client'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'client/build/'
